### ISSUE TITLE
Disable randomization for origin "human"

### ISSUE THREAD

**Issue by alinka62679** [QuantumXenon/origins-randomiser#14]
I have people on my server who want to play with origins and random, but there are those who don't want to. They naturally choose the origin "Human". Is it possible to make it so that the random mod doesn't work for them?
I'm sorry, my English is not very good

**Comment by QuantumXenon** [comment]
This is not currently a feature, but I will look into it for a future update

**Comment by QuantumXenon** [comment]
Sorry for the long wait! This has now been added and will be released with the next update.
