### ISSUE TITLE
Compatibility with Origin Layers

### ISSUE THREAD

**Issue by SocketKat** [QuantumXenon/origins-randomiser#15]
Suggestion: Add the ability to randomise each additional origin layer (ie [Origins: Classes](https://modrinth.com/mod/origins-classes)).

Currently each layer comes up to choose at join, and stays static throughout, regardless of when the base origin randomises.
It would be cool if the other layers could be randomised in addition to the base origins.

**Comment by QuantumXenon** [comment]
Sorry for the long wait! This has now been added and will be released with the next update.
