### ISSUE TITLE
[Bug] Player disconnecting due to duplicate scoreboard creation attempt invalidating NBT data

### ISSUE THREAD

**Issue by AdalynBlack** [QuantumXenon/origins-randomiser#16]
My friend and I are playing on a Fabric 1.20.2 server, and we added origin randomizer to it. I was able to join just fine, but my friend errors out when joining. This is the server log:
![image](https://github.com/QuantumXenon/origins-randomiser/assets/32852821/f8ee7b5b-6eff-45b1-9163-bc894560d541)
Their client didn't log any errors
It appears that the server is attempting to create a new scoreboard, erroring, then corrupting the player data, resulting in the player being unable to join. After removing the mod, they were sent back to world spawn with no items whatsoever

**Comment by QuantumXenon** [comment]
Sorry for the long wait! This is a strange issue as it (is supposed to) check if a scoreboard exists before creating it, so I don't know why this would be happening

**Comment by QuantumXenon** [comment]
As part of updating to 1.20.4, I rewrote the particular part of that would part affect this, so perhaps the new way is more robust at handling this. I will try to bring the change to other versions, so you could see if that helps once the update is released

**Comment by AdalynBlack** [comment]
Ok
thanks for taking a look at it. My sister and I are stuck on 1.20.2 until Origins and the rest of our mods are fully out for 1.20.4, so it'd be nice to have a fix in the meantime. For now I just have some command blocks set up to randomly pick one and tell us which one to use xD

**Comment by AdalynBlack** [comment]
Hi, I was just wondering if there are any updates on this issue
Have any fixes or potential fixes been pushed or released that we could test?

**Comment by QuantumXenon** [comment]
Hello! Sorry for the delay - please find attached a development version for 1.20.2 (this version only has the scoreboard changes ported at the moment). Could you please test this and see if you still have the same issue? I will port the remaining features and port to the other versions soon.

[origins-randomiser-2.5-dev+1.20.2.zip](https://github.com/user-attachments/files/15540598/origins-randomiser-2.5-dev%2B1.20.2.zip)

**Comment by QuantumXenon** [comment]
@AdalynBlack Do you have any updates on this?

**Comment by QuantumXenon** [comment]
This should now be fixed in the most recent version (v3.0) released today. If there are still issues, please reopen this issue
