### ISSUE TITLE
force specific origin on death

### ISSUE THREAD

**Issue by pocinhas** [QuantumXenon/origins-randomiser#17]
hey, i was wondering if you could add a config option to change the origin to a specific one every time a player dies?

asking for this since i want players to get the human origin when they die, and have to work back up again to whatever origin they want to choose, by crafting the origin orb. defaulting to the human origin feature is all i need now :)

**Comment by QuantumXenon** [comment]
This has now been added (resetting to `origins:human`) and so will be available in the next update
