### ISSUE TITLE
Enable/Disable Command

### ISSUE THREAD

**Issue by tmanfoo1** [QuantumXenon/origins-randomiser#3]
Hello! 

In my server we have a downtime part, where basically deaths dont count! I was curious if you could add a command to toggle to that within the game so that we dont have to restart the server when we want to go into the part where deaths dont count. 

I really enjoy the mod and would love to see this feature!

Thanks!

**Comment by QuantumXenon** [comment]
Thanks for the suggestion! I'll add this in the next update (though I am quite busy at the moment, so it might be in a while).

**Comment by tmanfoo1** [comment]
I really appreciate it :) Let me know if there is anything I can do to help. Also it would be nice to have the randomisation feature not require the deaths if possible. Currently we have deaths set at 1 million (because we use another mods death tracker), but it would be nice to not have to do that

**Comment by QuantumXenon** [comment]
Ok, I'll have a look at adding a config option for that too

**Comment by QuantumXenon** [comment]
@tmanfoo1 I've done a rewrite of the mod which now includes a new command `/toggleRandomiser` which should mean that you can turn origin randomisation on/off without having to do a server restart. There is still some testing I have to do, but a new version with the changes should be out soon.

**Comment by QuantumXenon** [comment]
@tmanfoo1 I've just released v2.0 on both CurseForge and Modrinth for all previously supported versions

**Comment by QuantumXenon** [comment]
> Also it would be nice to have the randomisation feature not require the deaths if possible. Currently we have deaths set at 1 million (because we use another mods death tracker), but it would be nice to not have to do that

I've just realised that I forgot to add this part. I won't be able to work on it again for a few weeks, but I'll include this in the next update. Sorry!

**Comment by QuantumXenon** [comment]
This is now included in the latest version (v2.1), which I've just releases on CurseForge and Modrinth

**Comment by tmanfoo1** [comment]
Wanted to say you thank you so much for the update! It is a huge quality of life improvement and I really appreciate it :)
