### ISSUE TITLE
enableLives command doesn't work

### ISSUE THREAD

**Issue by MaxyGames2** [QuantumXenon/origins-randomiser#4]
The command setLives does work but I can't use it without enableLives which does not work... this is not the only command that doesn't work though. There are only 4 commands that DO work and they are /randomise, /setLives, /setCommandUses and /toggleRandomiser

**Comment by QuantumXenon** [comment]
Sorry for any confusion, but `enableLives` is not a command, it is a config option. You can adjust it in `origins-randomiser.json` or in-game with Mod Menu.
