### ISSUE TITLE
Add Lives Command

### ISSUE THREAD

**Issue by EvanoriMemoria** [QuantumXenon/origins-randomiser#5]
Greetings!

I'm running a 1.19.2 server with your mod and would greatly appreciate a command to add a value of lives, with a similar format to the set Lives command. Loving the mod, thank you for your work.

**Comment by QuantumXenon** [comment]
I have added this to the mod in commit [5f20d2f](https://github.com/QuantumXenon/origins-randomiser/commit/5f20d2fddf3ca37609d4308d964bc9cc46b56da3).
I will bring it to all other versions soon

**Comment by EvanoriMemoria** [comment]
Wonderful! Thank you very much!
