### ISSUE TITLE
Gradle Build Failing 

### ISSUE THREAD

**Issue by EvanoriMemoria** [QuantumXenon/origins-randomiser#6]
It appears that https://ladysnake.jfrog.io/artifactory/mods free trial has expired. They appear to have a new website at https://ladysnake.org/ and repository at https://server.bbkr.space/artifactory/libs-release/. 

running `./gradlew build`:

<pre>
FAILURE: Build failed with an exception.
What went wrong:
A problem occurred configuring root project 'origins-randomiser'.`
`> Could not resolve all files for configuration ':modApi'.
   > Could not resolve dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.1.0.
     Required by:
         project : > com.github.MerchantPug:origins-fabric:v1.9.0
         project : > com.github.MerchantPug:origins-fabric:v1.9.0 > com.github.MerchantPug:apoli:2.8.0
      > Could not resolve dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.1.0.
         > Could not get resource 'https://ladysnake.jfrog.io/artifactory/mods/dev/onyxstudios/cardinal-components-api/cardinal-components-base/5.1.0/cardinal-components-base-5.1.0.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/ladysnake'. Received status code 409 from server: Conflict
   > Could not resolve dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.1.0.
     Required by:
         project : > com.github.MerchantPug:origins-fabric:v1.9.0
         project : > com.github.MerchantPug:origins-fabric:v1.9.0 > com.github.MerchantPug:apoli:2.8.0
      > Could not resolve dev.onyxstudios.cardinal-components-api:cardinal-components-entity:5.1.0.
         > Could not get resource 'https://ladysnake.jfrog.io/artifactory/mods/dev/onyxstudios/cardinal-components-api/cardinal-components-entity/5.1.0/cardinal-components-entity-5.1.0.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/ladysnake'. Received status code 409 from server: Conflict
   > Could not resolve io.github.ladysnake:PlayerAbilityLib:1.7.0.
     Required by:
         project : > com.github.MerchantPug:origins-fabric:v1.9.0 > com.github.MerchantPug:apoli:2.8.0
      > Could not resolve io.github.ladysnake:PlayerAbilityLib:1.7.0.
         > Could not get resource 'https://ladysnake.jfrog.io/artifactory/mods/io/github/ladysnake/PlayerAbilityLib/1.7.0/PlayerAbilityLib-1.7.0.pom'.
            > Could not GET 'https://landing.jfrog.com/reactivate-server/ladysnake'. Received status code 409 from server: Conflict
   > Could not resolve com.github.DaFuqs:AdditionalEntityAttributes:91da3dd.
     Required by:
         project : > com.github.MerchantPug:origins-fabric:v1.9.0 > com.github.MerchantPug:apoli:2.8.0
      > Could not resolve com.github.DaFuqs:AdditionalEntityAttributes:91da3dd.
         > Could not get resource 'https://ladysnake.jfrog.io/artifactory/mods/com/github/DaFuqs/AdditionalEntityAttributes/91da3dd/AdditionalEntityAttributes-91da3dd.pom'.
            > Could not HEAD 'https://landing.jfrog.com/reactivate-server/ladysnake'. Received status code 409 from server: Conflict

</pre>

**Comment by QuantumXenon** [comment]
This has been fixed now too by updating the maven repository
